### ISSUE TITLE
Hilti source build plugin error

### ISSUE THREAD

**Issue by ghuband** [rsmmr/hilti#42]
I'm building hilti with bro following the instructions on the web site:
http://www.icir.org/hilti/install/index.html

I'm building on Ubuntu 14.04 with clang 3.9.

I've successfully built bro.  I've run the bro tests and all passed.

During the hilti build I get the following error:

In file included from /home/user1/hilti/bro/src/Converter.cc:3:
/home/user1/hilti/bro/src/Plugin.h:50:71: error: non-virtual member function marked 'override' hides virtual member function
    int HookLoadFile(const std::string& file, const std::string& ext) override;
                                                                      ^
/home/user1/bro/src/plugin/Plugin.h:644:14: note: hidden overloaded virtual function 'plugin::Plugin::HookLoadFile' declared here:
      different number of parameters (3 vs 2)
        virtual int HookLoadFile(const LoadType type, const std::string& file, const std::string& resolved);

**Comment by rsmmr** [comment]
Which Bro version is that, git master? It should work with 2.5 but master has some incompatible changes.

**Comment by ghuband** [comment]
OK, I checked out v2.5 of bro, then I built bro:
> CXX="/usr/bin/clang++ --stdlib=libc++" ./configure && make
No errors.  Then I ran the bro tests:
> cd testing> CXX="/usr/bin/clang++ --stdlib=libc++" make[58%] plugins.hooks ... failed[58%] istate.broccoli-ipv6 ... failed
No other errors.
I'll try building hilti with bro tonight.
Thanks
Gary 

    On ‎Thursday‎, ‎April‎ ‎19‎, ‎2018‎ ‎04‎:‎33‎:‎39‎ ‎PM‎ ‎EDT, Robin Sommer <notifications@github.com> wrote:  
 
 
Which Bro version is that, git master? It should work with 2.5 but master has some incompatible changes.

**Comment by ghuband** [comment]
hilti built with no errors.
When I try to run the tests:
> cd tests> makebtest -j -f diag.logmake: btest: Command not foundmake: *** [tests] Error 127

Gary 

    On ‎Thursday‎, ‎April‎ ‎19‎, ‎2018‎ ‎04‎:‎33‎:‎39‎ ‎PM‎ ‎EDT, Robin Sommer <notifications@github.com> wrote:  
 
 
Which Bro version is that, git master? It should work with 2.5 but master has some incompatible changes.

**Comment by rsmmr** [comment]
You need btest: https://www.bro.org/development/README.btest.html

**Comment by ghuband** [comment]
Thanks.
> git clone https://github.com/bro/btest
> cd btest> sudo python setup.py install
Now I can go into hilti/testing:
> make hello-worldsall 2 tests successful> make all(some failed and failed expected)139 of 892 tests failed, 8 skipped

Is this normal? 

    On ‎Friday‎, ‎April‎ ‎20‎, ‎2018‎ ‎11‎:‎04‎:‎36‎ ‎AM‎ ‎EDT, Robin Sommer <notifications@github.com> wrote:  
 
 
You need btest: https://www.bro.org/development/README.btest.html
